import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    barra: {
      height: '10%',
      backgroundColor: '#07055C',
      justifyContent: 'center',    
    },
    entrar: {
      fontSize : 20,
      color: '#FFFF',
      fontFamily: 'Quicksand',
      top: '-20%',
      left: '41%',
    },
    email: {
      width: '92%',
      height: '30%',
      top: '10%',
      left: '4%',
      borderColor: '#A4A2AA',
      borderRadius: 9.5,
      borderWidth: 1, 
      justifyContent: 'center',
      fontSize: 18,  
      fontFamily: 'Inter', 
    },
    senha: {
      width: '92%',
      height: '30%',
      top: '-50%',
      left: '4%',
      borderColor: '#A4A2AA',
      borderRadius: 9.5,
      borderWidth: 1, 
      justifyContent: 'center',
      fontSize: 18,  
      fontFamily: 'Inter', 
    },
    botaoNaoCadastrado: {
      borderWidth: 1,
      backgroundColor: '#FFB6C1',
      borderColor: '#A4A2AA',
      borderRadius: 6,
      width: '92%',
      height: '9%',
      left: '4%',
      top: '-12%',
      justifyContent: 'center',
    },
    botaoGoogle: {
      borderWidth: 1,
      borderColor: '#A4A2AA',
      borderRadius: 6,
      width: '92%',
      height: '9%',
      left: '4%',
      top: '-12%',
      justifyContent: 'center',
    },
    cortextologin: {
      color: '#000000',
      fontSize: 16,  
      fontFamily: 'Inter',
      left: '27%',
    },
    botaologin: {
      width: '88%',
      height: '10%',
      left: '6%',
      top: '-8%',
      borderRadius: 25,
      backgroundColor: '#07055C',
      justifyContent: 'center',
      alignItems: 'center',
    },
    cortextologin2: {
      color: '#FFFF',
      fontSize: 16,  
      fontFamily: 'Inter',
    },
    logo1: {
      width: 20,
      height: 20,
      left: '14%',
      top: '-18%',
      justifyContent: 'center',
    },
    logo2: {
      width: 20,
      height: 20,
      left: '14%',
      top: '-18%',
      justifyContent: 'center',
    },
    seta: {
      top: '15%',
      left: '6%',
    },
      
  });